### ISSUE TITLE
运行不了了吗

### ISSUE THREAD

**Issue by lxp969** [greats3an/qqsolitaire#1]
提示![Screenshot_20210906-120122.jpg](https://user-images.githubusercontent.com/84167658/132158957-44eb0873-c81e-4e1c-824f-fde34cbb8056.jpg)

**Comment by greats3an** [comment]
记得参数加引号：

`./qd "qz_referer...."`

**Comment by lxp969** [comment]
![Screenshot_20210907-230233.jpg](https://user-images.githubusercontent.com/84167658/132367555-80c270d4-2302-4a96-b455-3c5ccf35e4a9.jpg)还是运行不了

**Comment by greats3an** [comment]
> ![Screenshot_20210907-230233.jpg](https://user-images.githubusercontent.com/84167658/132367555-80c270d4-2302-4a96-b455-3c5ccf35e4a9.jpg)还是运行不了

删掉`［`   `］`，和这个格式一致：

> 记得参数加引号：
> 
> `./qd "qz_referer...."`

最好把截图打个码，你这信息能让别人登陆你的qq了🤔

**Comment by lxp969** [comment]
哥，是我群的分享链接有问题吗，好像是一直在报错python: can't open file '/data/data/com.termux/files/home/，还是我python没安装好

**Comment by greats3an** [comment]
更新了下，再安装一次吧：`bash <(curl -s https://raw.githubusercontent.com/greats3an/qqsolitaire/master/installer.sh)`

这次cookie在`qd`里改

这点东西太久没动过了，带来麻烦还请抱歉

**Comment by lxp969** [comment]
- [ ] 还是报错

**Comment by greats3an** [comment]
> * [ ]  还是报错![Screenshot_20210908-104507.jpg](https://user-images.githubusercontent.com/84167658/132438212-ec65d150-5fae-480b-9856-dc1dcc465245.jpg)

vpn断了

**Comment by lxp969** [comment]
好了，谢谢
